apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
        - name: api-server
          image: my-api-server:v1
          ports:
            - containerPort: 3000
          env:
            - name: KAFKA_BROKER
              value: kafka-broker:9092
            - name: MONGO_URI
              value: mongodb://mongo:27017
---
apiVersion: v1
kind: Service
metadata:
  name: api-server
spec:
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32000
  selector:
    app: api-server
  type: NodePort
